### ISSUE TITLE
No wheelchair for single amputee

### ISSUE THREAD

**Issue by CrystalNole** [HypatiaStation/HypatiaNEW#12]
So I tested this on both the new and old code, and if you have only a single leg missing, you spawn on the floor, unable to do anything but talk or switch hands, even if you spawn in a chair you can't buckle yourself. This could be fixed by giving the people with one one missing leg the same wheelchair spawn as people that are missing two legs get.

**Comment by torger597** [comment]
The reason this is is the code checks for both feet being missing or destroyed. Adjusting it to look for either missing foot should solve this issue, applying that as a fix now.

**Comment by torger597** [comment]
Fixed in my latest pull.
