### ISSUE TITLE
Gravity Generator SMES in/outpu

### ISSUE THREAD

**Issue by CrystalNole** [HypatiaStation/HypatiaNEW#13]
The gravity generator SMES has an input of 50,000 W while having a maximum output of 250,000. While the generator does not take much power, setting it too high may output too much energ at once, thus draining it faster than it can charge.

http://prntscr.com/813u3r

**Comment by torger597** [comment]
This can be left alone, as it's a minor issue that can be solved ICly as part of maintenance on the part of Engineering every round.

**Comment by CrowOfBourbon** [comment]
This has been fixed... Or I was told it was fixed.
