### ISSUE TITLE
[Map][Bug] Gas cooling system in Telecomms Satellite (Telecomms Control Room) is not connected to gas pipes.

### ISSUE THREAD

**Issue by torger597** [HypatiaStation/HypatiaNEW#26]
Location of Bug:Telecomms
What sort of bug is it? (Atmospherics, Wiring etc): Atmospherics
How severe is the bug? [Low, Medium, High, Game Breaking]: High

**Comment by Ltmayday** [comment]
going to fix that when i got the update of the new fixes..will update the doc when done

**Comment by Ltmayday** [comment]
fixed
