### ISSUE TITLE
[Bug][Code] Duty Officer 

### ISSUE THREAD

**Issue by uoheinrich** [HypatiaStation/HypatiaNEW#35]
description of the Bug: Duty Officer permissions are not available for selection.
What were you doing when the bug happened: Attempting to give permissions.
What was the expected result of your actions: To give a player Duty Officer permissions.
What actually happened: No permissions were available for selection
Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself: 10/10
Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]: Game Breaking

**Comment by torger597** [comment]
Should be fixed in next PR.

**Comment by CrowOfBourbon** [comment]
Closing this. Will reopen if it isn't fixed in the next PR.
