### ISSUE TITLE
[Bug][Map]Airlock near Command Dorms is not constructed at all

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaNEW#36]
Byond Key:
 Location of Bug:Airlock in maintenance near Command Dorms
 What sort of bug is it? (Atmospherics, Wiring etc):A couple of each. There is just two doors without any actual airlock cycling.
 Is there a special way to replicate this bug in the map?:I think it built that way
 How severe is the bug? [Low, Medium, High, Game Breaking]:Low to medium
![bug](https://cloud.githubusercontent.com/assets/13021339/9235559/1a500228-4148-11e5-9db3-76b5a00d1535.jpg)

 Please attach a screenshot of the affected area:

**Comment by Ltmayday** [comment]
fixed...i turned that small area into a manintenance room whats holding gear on racks
