### ISSUE TITLE
[Code][Bug]Bank account creation date.

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaNEW#37]
Description of the Bug:Bank account creation date is "Your account was created: 6:50, 22 August, 2425 at NTGalaxyNet Terminal #464"
 What were you doing when the bug happened:Pressed "Notes" in "IC" tab.
 What was the expected result of your actions:See something closer to lore-wise time.
 What actually happened:"Your account was created: 6:50, 22 August, 2425 at NTGalaxyNet Terminal #464"
 Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself:10/10
 Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]:Low to high, depends on how you see importance of it to RP.

**Comment by Zurro13** [comment]
Well, really i wasn't expecting to see anything at all, as i was playing robot at this moment.

**Comment by torger597** [comment]
The reason this is so is the code that creates the date for account creation, etc is currently this:
current_date_string = "[num2text(rand(1,31))] [pick("January","February","March","April","May","June","July","August","September","October","November","December")], [game_year]"
The game_year is created like this:
var/game_year = (text2num(time2text(world.realtime, "YYYY")) + 544)
It's a start, but this is a low-priority issue until I can get this fixed up.
But what I will do is adjust it so it's a little past 3000, until I get closer to the real date.

**Comment by JakeRamsay** [comment]
I believe it needs to be set to 
var/game_year = (text2num(time2text(world.realtime, "YYYY")) + 1090)
for the year 3105
