### ISSUE TITLE
[Suggestion][Code]Milky Milk.

### ISSUE THREAD

**Issue by TrueDARK** [HypatiaStation/HypatiaNEW#38]
Description of the Suggestion: Re-Add milk to the Soda-fountain drink Selection.
Examples of how it'd enhance the game-play: It makes one not worry about running out of milk. And allows me to cause a Cheese-apocalypse.

**Comment by CrowOfBourbon** [comment]
Strongly suggest against this because making 400 cheese wheels for no apparent reason doesn't suit heavy RP.
