### ISSUE TITLE
[Bug][Map] Kitchen Button

### ISSUE THREAD

**Issue by TrueDARK** [HypatiaStation/HypatiaNEW#40]
Byond Key:TrueDARK
Location of Bug:Kitchen Wall. Right side button.
What sort of bug is it? (Atmospherics, Wiring etc): Broken Button. 
Is there a special way to replicate this bug in the map?: Pressing it. 
How severe is the bug? [Low, Medium, High, Game Breaking]:Low
Please attach a screenshot of the affected area:Nothing to really look at.

**Comment by HappyKitten** [comment]
Button on table (left side works) button on table (right does not).

**Comment by HappyKitten** [comment]
Potentially fixed. Needs tested

**Comment by CrowOfBourbon** [comment]
Closing with the right milestone. This will be reopened if not fixed.

**Comment by HappyKitten** [comment]
This needs reopened, however I am working on it

**Comment by HappyKitten** [comment]
Is now fixed. Someone please close.
