### ISSUE TITLE
[Bug][Sprite/Code] Missing Seed/plant Icons

### ISSUE THREAD

**Issue by TrueDARK** [HypatiaStation/HypatiaNEW#43]
I will place any missing plant icons I find here.
Peanuts have no seed Icon or growth icons. They have item Icons, tho.
Amanita Mushrooms have no final growth stage Icon.
Tower Cap Mushrooms have no Pre-Maturity stage icons.
Chanterelle Mushrooms have no final growth stage icon
Plump Hemet Mushrooms have no Final growth stage Icon

**Comment by torger597** [comment]
Should be fixed in my next PR, assuming plants were ported properly.
Assuming.

**Comment by TrueDARK** [comment]
Cool. Thanks.

**Comment by torger597** [comment]
That's something that'd have to be sprited.

**Comment by TrueDARK** [comment]
Yup. Also make sure that Strawberries don't fuckup like they did on that other code.
