### ISSUE TITLE
[Suggestion][Map] Luminosity too low. 

### ISSUE THREAD

**Issue by TrueDARK** [HypatiaStation/HypatiaNEW#44]
Byond Key:TrueDARK
What do you feel is wrong with the map?:Hydro needs a Makeover.
What is the cause of the problem? (Wiring, Atmospherics, Placement ePlacement, mostly.
What do you think could be done about it?: The trays need more light, the Light Panels should be placed back under them. Also, the Chef has no way to grow plants without Breaking in. 
Please include a screenshot of the area you feel needs to be changed: ALL THE HYDRO

**Comment by HappyKitten** [comment]
TrueDark, I will be adding light trays to hydro, however due to hydro not being a subset of assistant, and you not being very specific otherwise about "It's awful" I'm not sure what you want.

**Comment by HappyKitten** [comment]
Put in light trays

**Comment by CrowOfBourbon** [comment]
Closing until further notice. it appears Kitty fixed Hydro.
