### ISSUE TITLE
[Code][Suggestion]I'mma kick th' Buckets

### ISSUE THREAD

**Issue by TrueDARK** [HypatiaStation/HypatiaNEW#45]
Description of the Suggestion:Currently. Buckets hold 70u of water. Hydro Trays need 100. The trays also don't prevent overflow. It needs to be increased to atleast 100U Capacity.
Examples of how it'd enhance the game-play:No more double trips. Or water waste.

**Comment by CrowOfBourbon** [comment]
Just fill the bucket twice. Not a code issue. Sorry.
