### ISSUE TITLE
[Map][Bug?] Problems with telecomms cooling, if this setup is actual

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaNEW#61]
Byond Key:Zurro13
 Location of Bug:Telecomms satellite
 What sort of bug is it? (Atmospherics, Wiring etc):Atmospherics/Machinery settings
 Is there a special way to replicate this bug in the map?:Well ... it is there for now.
 How severe is the bug? [Low, Medium, High, Game Breaking]:low to high, depends on how much cooling is needed.
 Please attach a screenshot of the affected area:
![tcommsat](https://cloud.githubusercontent.com/assets/13021339/9292768/72c32836-4413-11e5-8148-2da26222c956.jpg)

Cooler was turned off, cooling temperature was set to 293C, and siphoning vent set to 101kPa external pressure, while there was less then 30kPa in chamber. 
To make this work, there is choice between adjusting vent settings or filling chamber with more gas, so there will be enough pressure for vent to start siphoning and cooler to start work, assuming it will be turned on and set to required cooling temp.

**Comment by Ltmayday** [comment]
i take a look as i was the one working on this

**Comment by Ltmayday** [comment]
ok i hope this is fixed...testing now

**Comment by Ltmayday** [comment]
Added a canister setup in the Anomalous Materials at Tcomms and piped it to the cooling system,

Temp Workround intill i can find a better way to make this work

pr sent
