### ISSUE TITLE
[Bug][Map]Hydroponics APC connection broken

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaNEW#62]
Byond Key:Zurro13
 Location of Bug:Hydroponics
 What sort of bug is it? (Atmospherics, Wiring etc):Wiring
 Is there a special way to replicate this bug in the map?:No need to have special way.
 How severe is the bug? [Low, Medium, High, Game Breaking]:Low to high, depends on botanist.
 Please attach a screenshot of the affected area:
![hydroponics](https://cloud.githubusercontent.com/assets/13021339/9294451/96e86b16-4456-11e5-9e4c-4dcbc5e226c9.jpg)

**Comment by HappyKitten** [comment]
So this is a bit confusing, because by my screen, and testing, they work. I'm looking at it now. And I just pulled from the github. So it should work.
